export const GET_STUFFS = 'GET_STUFFS';

export const GET_CATEGORIES = 'GET_CATEGORIES';

export const SIGNIN_RESULT_SUCCESS = "SIGNIN_RESULT_SUCCESS";
export const SIGNIN_RESULT_ERROR = "SIGNIN_RESULT_ERROR";
export const SIGNIN_RESULT_RESET = "SIGNIN_RESULT_RESET";
export const SIGNUP_RESULT_SUCCESS = "SIGNUP_RESULT_SUCCESS";
export const SIGNUP_RESULT_ERROR = "SIGNUP_RESULT_ERROR";
export const SIGNUP_RESULT_RESET = "SIGNUP_RESULT_RESET";
export const SIGNOUT = "SIGNOUT";