export const UPDATE_STUFFS = 'UPDATE_STUFFS';
export const RATE_STUFF = 'RATE_STUFF';
export const FILTER_STUFFS = 'FILTER_STUFFS';

export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';

export const BASKET_UPDATE = 'BASKET_UPDATE';

export const SIGNIN_RESULT_SUCCESS = "SIGNIN_RESULT_SUCCESS";
export const SIGNIN_RESULT_ERROR = "SIGNIN_RESULT_ERROR";
export const SIGNIN_RESULT_RESET = "SIGNIN_RESULT_RESET";
export const SIGNUP_RESULT_SUCCESS = "SIGNUP_RESULT_SUCCESS";
export const SIGNUP_RESULT_ERROR = "SIGNUP_RESULT_ERROR";
export const SIGNUP_RESULT_RESET = "SIGNUP_RESULT_RESET";
export const SIGNOUT = "SIGNOUT";